name: install nginx on ec2 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-nginx-via-runner:
    runs-on: self-hosted
    steps:

      # - name: ssh to instance
      #   run: ssh ${{secrets.KEY}} noor@51.20.134.222

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            if command -v docker &>/dev/null; then
              echo "Docker is installed."
            else
              chmod +x script.sh && bash script.sh 
            fi
            docker rm -f $(docker ps -aq)
            docker run -d -p 80:80 nginx