name: install nginx on ec2 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-nginx-via-runner:
    runs-on: ip-172-31-31-85
    steps:

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            if command -v docker &>/dev/null; then
              echo "Docker is installed."
            else
              sudo apt update -y
              sudo apt  install docker.io -y
              sudo usermod -aG docker $USER
              newgrp docker 
              sleep 10
              sudo systemctl start docker
            fi
            docker rm -f $(docker ps -aq)
            docker run -d -p 80:80 nginx
