name: install nginx on ec2 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-nginx-via-runner:
    runs-on: self-hosted
    steps:
      - name: install sshpass
        run: sudo apt-get install sshpass

      - name: ssh to instance
        run: sshpass -p "123" ssh noor@51.20.134.222

      - name: echo username
        run: echo $USER
      - name: Check if Docker is installed
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
          else
            echo "Docker is not installed."
          fi

      - name: Set up Docker
        if: steps.check.outputs.stdout == 'Docker is not installed.'
        uses: docker/setup-buildx-action@v1

      - name: Check Docker version
        run: docker --version 

      - name: delete previously running containers
        run: docker rm -f $(docker ps -aq)

      - name: run nginx containers
        run: docker run -d -p 80:80 nginx